### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdGuardExtra#111]
Pre-roll ads - https://github.com/AdguardTeam/AdguardFilters/issues/64754#issuecomment-700364742

Example link -  [https://www.twitch.tv/twitchmedia39](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.twitch.tv/twitchmedia39)

**Comment by berkant** [comment]
Are you planning on doing anything about this? At this moment, there is a bazillion of reports on AdguardTeam/AdguardFilters#77344.

I believe AdGuard can deploy a number of proxy servers in exotic locations or where Twitch ads claimed to not appear (e.g. Russia, and maybe CIS states), and redirect Usher requests over those servers. There are working extensions doing this, and I suppose people would pretty much rather going over AdGuard's servers instead of some random people's servers. See: https://github.com/pixeltris/TwitchAdSolutions#recommendations.
