### ISSUE TITLE
Блокировка Suggested posts и рекламы в ленте Facebook

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdGuardExtra#171]
Здравствуйте. 

Поскольку мой предыдущий запрос поспешили закрыть после 2 месяцев мурыжения, а проблема осталась, дублирую свой запрос повторно.

Прошу ознакомиться с исходным запросом и моим комментарием в самом конце обсуждения:
https://github.com/AdguardTeam/AdGuardExtra/issues/159

С уважением.

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/159#issuecomment-800491400
> А вот реклама с правой стороны осталась...
https://fastpic.ru/view/114/2021/0316/681a05392e5b7a17f9b6a98a5ad118e7.jpg.html

Эта реклама блокируется в Базовом фильтре, для которого нужно использовать наше расширение или программу.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/111527131-a3418880-8770-11eb-9950-0fcac0fa0978.png)

</details><br/>

Если у вас эта проблема осталась до сих пор, отправьте репорт через эту [форму](https://agrd.io/report). Там будет указана более полная информация.

**Comment by jbionic2016** [comment]
Скажите, а есть какая-то разница в том какую последовательность действий я совершаю прежде чем открыть ленты Фейсбука? Дело в том, что я куда чаще открываю Мессенджер Фейсбука, нежели ленту. А если и открываю ленту Фейсбука, чтоб посмотреть посты из подписок, то делаю это опять таки из Мессенджера путём нажатия на кнопку с Домиком, как показано на первом скриншоте ниже: https://fastpic.ru/fullview/114/2021/0318/679217f54c3ab558937db8f43597f19a.jpg.html

Вот и сейчас я в целях сравнения сначала открыл Фейсбук напрямую, напечатав в адресной строке браузера адрес: facebook.com - и никакой рекламы с правой стороны от моей новостной ленты не обнаружилось. А когда я активировал в Хроме Ваше расширение Adguard Extra с зашёл, как обычно делаю, в Ленту Фейсбука из Месседжера путём клика на кнопку с Домиком, то рядом с Лентой сразу же показалась реклама: https://fastpic.ru/fullview/114/2021/0318/8494537cf5b7b758f5435bb9df9febf4.jpg.html

**Comment by zloyden** [comment]
Согласно текущему коду, включение/выключение экстры никак не влияет на появление этой рекламы, поскольку она блокируется в фильтрах.


> Скажите, а есть какая-то разница в том какую последовательность действий я совершаю прежде чем открыть ленты Фейсбука?

Шаги воспроизведения играют большую роль, но, к сожалению, это не повторяется у меня.

Репорт я ваш увидел, уже ответил в нем и давайте перенесем обсуждение туда. Его также должны рассмотреть мои коллеги.

**Comment by jbionic2016** [comment]
Да, Вы похоже правы, что дело оказалось в одном из расширений внутри Хрома. И Вы не поверите в каком. PrivacyBadger!! Я провёл несколько экспериментов, включая эксперимент, когда я включил ВСЕ свои Хром-расширения, кроме PrivacyBadger, и рекламы при этом не было. Как только включаю PrivacyBadger, то реклама сразу же проникает в браузер. Её можно отключить, если в расширении uMatrix  выключить scontent.xx.fbcdn.net для Image, как показано на скриншоте ниже: https://fastpic.ru/fullview/114/2021/0318/0ff5efee37de167f553ef8808a2f66b6.jpg.html  

Я не знаю, нужно ли в связи с этим создавать какие-то правила в Adguard. Хотя подозреваю, что у многих пользователей Adguard расширение PrivacyBadger тоже может быть установлено.

**Comment by zloyden** [comment]
Рад, что теперь все выяснилось. В этом случае мы рекомендуем использовать только наше расширение для браузера или программу во избежание подобных конфликтов.

**Comment by ghostwords** [comment]
Hi, I think this is a conflict between Privacy Badger's [link tracking protection on Facebook](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking) ([source code](https://github.com/EFForg/privacybadger/blob/70b161cfcd5f5d981cf07333eed558f95463e230/src/js/firstparties/facebook.js)) and AdGuard Extra.

Privacy Badger looks for outbound tracking links on Facebook and removes tracking attributes. AdGuard Extra looks for ad containers and hides the ads. It's possible that Privacy Badger sometimes removes tracking attributes from ads before AdGuard Extra gets a look, and then AdGuard Extra ends up missing those ads because the attributes AdGuard Extra looks for are no longer present.

As a workaround, users of AdGuard Extra and Privacy Badger can disable Privacy Badger on Facebook.

To disable Privacy Badger on Facebook while keeping Privacy Badger enabled and protecting you elsewhere by clicking on the "Disable Privacy Badger for this site" button in Privacy Badger's popup while on Facebook.
